version: 2

sources:
  - name: Supermarket
    database: mineria-2023-402723
    tables:
      - name: Clientes
        description: tabla con la información de los clientes
      - name: Compras
        description: tabla con la información de las compras hechas por clientes
      - name: Exito
        description: tabla con la información de los productos de la tienda Exito
      - name: Olimpica_IMP
        description: tabla con la información de los productos de la tienda Olimpica
      - name: Olimpica
        description: tabla con la información de los productos de la tienda Olimpica
      - name: Olimpica_EXT
        description: tabla con la información de los productos de la tienda Olimpica  
      - name: Clientes_EXT
        description: tabla con la información de los productos de la tienda Olimpica  
      - name: Compras_EXT
        description: tabla con la información de los productos de la tienda Olimpica  
      - name: Exito_EXT
        description: tabla con la información de los productos de la tienda Olimpica  